# Config Options:
# https://spaceship-prompt.sh/config/intro/

SPACESHIP_DOCKER_COMPOSE_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_KUBECTL_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_PACKAGE_SHOW=false

SPACESHIP_DIR_TRUNC_REPO=false

# Enable time section
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT="%D{%a %H:%M:%S}"
SPACESHIP_TIME_12HR
