import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95
startup_mode = "Maximized"
