set -g mouse on
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"

set -g prefix ^A
set -g base-index 1
set -g detach-on-destroy off
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
set -s escape-time 0
set -g history-limit 50000
set -g focus-events on

# create splits
bind-key | split-window -h
bind-key - split-window -v

# navigate splits
bind-key -n C-h if -F "#{pane_at_left}"   "" "select-pane -L"
bind-key -n C-j if -F "#{pane_at_bottom}" "" "select-pane -D"
bind-key -n C-k if -F "#{pane_at_top}"    "" "select-pane -U"
bind-key -n C-l if -F "#{pane_at_right}"  "" "select-pane -R"

# dont break moving commits in lazygit
bind-key -n C-j if-shell "[ #{pane_current_command} = lazygit ]" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "[ #{pane_current_command} = lazygit ]" "send-keys C-k"  "select-pane -U"

# Vi copypaste mode
set -g mode-keys vi
bind-key -T copy-mode-vi 'Escape' send -X cancel
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

# List of plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

# catppuccin conf
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
# this + rounded cases wierd reverse issue:
# https://github.com/catppuccin/tmux/discussions/406 
set -g @catppuccin_status_background "none"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# status conf, must be after the `run`
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_cpu}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

