start-at-login = true

after-startup-command = [
  'exec-and-forget borders'
]

# Gaps configuration - minimal like Omarchy's clean aesthetic
[gaps]
  inner.horizontal = 8
  inner.vertical = 8
  outer.left = 8
  outer.bottom = 8
  outer.top = 8
  outer.right = 8

[key-mapping]
  preset = 'qwerty'

# Main binding mode - using alt as primary modifier to avoid macOS conflicts
# (alt is less used by macOS system shortcuts compared to cmd)
[mode.main.binding]

  alt-g = '''exec-and-forget open -a "Ghostty"'''
  alt-v = '''exec-and-forget open -a "Brave"'''
  alt-b = '''exec-and-forget open -a "Google Chrome"'''
  alt-f = '''exec-and-forget open -a "Finder"'''
  alt-i = '''exec-and-forget open -a "Messages"'''
  alt-s = '''exec-and-forget open -a "Slack"'''

  alt-slash = 'layout tiles horizontal vertical'
  alt-comma = 'layout accordion horizontal vertical'

  alt-h = 'focus left'
  alt-j = 'focus down'
  alt-k = 'focus up'
  alt-l = 'focus right'

  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'

  alt-minus = 'resize smart -50'
  alt-equal = 'resize smart +50'
  alt-shift-minus = 'resize smart -100'
  alt-shift-equal = 'resize smart +100'

  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  alt-4 = 'workspace 4'

  alt-w = 'workspace W'  # Web/Browser workspace
  alt-d = 'workspace D'  # Development/IDE workspace  
  alt-m = 'workspace M'  # Misc workspace
  alt-c = 'workspace C'  # Chat workspace
  alt-t = 'workspace T'  # Terminal

  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'
  alt-shift-4 = 'move-node-to-workspace 4'

  alt-shift-w = 'move-node-to-workspace W'
  alt-shift-d = 'move-node-to-workspace D'
  alt-shift-m = 'move-node-to-workspace M'
  alt-shift-c = 'move-node-to-workspace C'
  alt-shift-t = 'move-node-to-workspace T'

  alt-tab = 'workspace-back-and-forth'
  alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

  alt-shift-f = 'layout floating tiling'
  alt-ctrl-shift-f = 'fullscreen'
  alt-shift-semicolon = 'mode service'

# Application-specific workspace assignments (Omarchy-style organization)
[[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  run = 'move-node-to-workspace W'

[[on-window-detected]]
  if.app-id = 'com.brave.Browser'
  run = 'move-node-to-workspace W'

[[on-window-detected]]
  if.app-id = 'com.jetbrains.intellij'
  run = 'move-node-to-workspace D'

[[on-window-detected]]
  if.app-id = 'com.microsoft.VSCode'
  run = 'move-node-to-workspace D'

[[on-window-detected]]
  if.app-id = 'com.mitchellh.ghostty'
  run = 'move-node-to-workspace T'

# Float certain dialogs and utility windows by default
[[on-window-detected]]
  if.app-id = 'com.apple.finder'
  run = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.1password.1password-macos'
  run = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.apple.MobileSMS'
  run = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.tinyspeck.slackmacgap'
  run = 'move-node-to-workspace C'

# Monitor assignments for multi-monitor setups (if applicable)
[workspace-to-monitor-force-assignment]
  W = 'main'
  D = 'main'
  T = 'main'        
  M = 'secondary'
  C = 'secondary'

  1 = 'main'
  2 = 'main'
  3 = 'secondary'
  4 = 'secondary'

# Service mode for system operations and advanced window management
[mode.service.binding]
  esc = ['reload-config', 'mode main']
  r = ['flatten-workspace-tree', 'mode main']                 # Reset layout
  f = ['layout floating tiling', 'mode main']                 # Toggle floating
  backspace = ['close-all-windows-but-current', 'mode main']  # Close all but current

  # Advanced window joining (like Hyprland's window grouping)
  alt-shift-h = ['join-with left', 'mode main']
  alt-shift-j = ['join-with down', 'mode main'] 
  alt-shift-k = ['join-with up', 'mode main']
  alt-shift-l = ['join-with right', 'mode main']

  down = 'volume down'
  up = 'volume up'
  shift-down = ['volume set 0', 'mode main']

